### ISSUE TITLE
Hubot install on Windows 8.

### ISSUE THREAD

**Issue by sarathsps0327** [hubotio/generator-hubot#56]
Hi,

I am trying to install the hubot on Windows 8.0.
I completed the below steps without any issues,

```
npm install -g yo generator-hubot
mkdir myhubot
% cd myhubot
```

I am trying to use Hipchat as the adapter for this.
When I executed the below command
`yo hubot`

I am getting the below error. Please see the detailed attached.

```
C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp-client\node
_modules\node-xmpp-core\node_modules\node-stringprep\build\node_stringprep.vcxp
roj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props"
 was not found. Confirm that the path in the <Import> declaration is correct, a
nd that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
```

Looking at the error it looks like I need to install Visual C++ for this. Can you please confirm the same?

Please see the detailed error below

```
-----------------------------------------------------------------------------------------------------------------------------------
C:\Partha\myhubot>yo hubot
                     _____________________________
                    /                             \
   //\              |      Extracting input for    |
  ////\    _____    |   self-replication process   |
 //////\  /_____\   \                             /
 ======= |[^_/\_]|   /----------------------------
  |   | _|___@@__|__
  +===+/  ///     \_\
   | |_\ /// HUBOT/\\
   |___/\//      /  \\
         \      /   +---+
          \____/    |   |
           | //|    +===+
            \//      |xx|

? Owner: (User <user@example.com>) sarathsps@gmail.com
? Owner: sarathsps@gmail.com
? Bot name: aemhubot
? Description: A simple helpful robot for your Company
? Bot adapter: (campfire) hipchat
? Bot adapter: hipchat
   create bin\hubot
   create bin\hubot.cmd
   create Procfile
   create README.md
   create external-scripts.json
   create hubot-scripts.json
   create .gitignore
   create package.json
   create scripts\example.coffee
   create .editorconfig
                     _____________________________
 _____              /                             \
 \    \             |   Self-replication process   |
 |    |    _____    |          complete...         |
 |__\\|   /_____\   \     Good luck with that.    /
   |//+  |[^_/\_]|   /----------------------------
  |   | _|___@@__|__
  +===+/  ///     \_\
   | |_\ /// HUBOT/\\
   |___/\//      /  \\
         \      /   +---+
          \____/    |   |
           | //|    +===+
            \//      |xx|

npm WARN engine hubot-hipchat@2.12.0: wanted: {"node":"~0.12.2"} (current: {"nod
e":"4.1.0","npm":"2.14.3"})
\
> node-stringprep@0.7.2 install C:\Partha\myhubot\node_modules\hubot-hipchat\nod
e_modules\node-xmpp-client\node_modules\node-xmpp-core\node_modules\node-stringp
rep
> node-gyp rebuild


C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp-client\node_
modules\node-xmpp-core\node_modules\node-stringprep>if not defined npm_config_no
de_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\n
ode_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.


C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp-client\node
_modules\node-xmpp-core\node_modules\node-stringprep\build\node_stringprep.vcxp
roj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props"
 was not found. Confirm that the path in the <Import> declaration is correct, a
nd that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp
-client\node_modules\node-xmpp-core\node_modules\node-stringprep
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> node-stringprep@0.7.2 install C:\Partha\myhubot\node_modules\hubot-hipchat\nod
e_modules\node-xmpp-core\node_modules\node-stringprep
> node-gyp rebuild


C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp-core\node_mo
dules\node-stringprep>if not defined npm_config_node_gyp (node "C:\Program Files
\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-
gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp-core\node_m
odules\node-stringprep\build\node_stringprep.vcxproj(20,3): error MSB4019: The
imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that t
he path in the <Import> declaration is correct, and that the file exists on dis
k.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp
-core\node_modules\node-stringprep
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
/
> iconv@2.1.11 install C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules
\node-xmpp-core\node_modules\ltx\node_modules\node-expat\node_modules\iconv
> node-gyp rebuild


C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp-core\node_mo
dules\ltx\node_modules\node-expat\node_modules\iconv>if not defined npm_config_n
ode_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\
node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp-core\node_m
odules\ltx\node_modules\node-expat\node_modules\iconv\build\libiconv.vcxproj(20
,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was n
ot found. Confirm that the path in the <Import> declaration is correct, and tha
t the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Partha\myhubot\node_modules\hubot-hipchat\node_modules\node-xmpp
-core\node_modules\ltx\node_modules\node-expat\node_modules\iconv
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "hubot" "hubot-scripts" "hubot-dia
gnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-goo
gle-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hub
ot-shipit" "hubot-hipchat" "--save"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! node-stringprep@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-stringprep@0.7.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Partha\myhubot\npm-debug.log

C:\Partha\myhubot>
-----------------------------------------------------------------------------------------------------------------------------------
```

**Comment by technicalpickles** [comment]
> Looking at the error it looks like I need to install Visual C++ for this. Can you please confirm the same?

I don't have access to a Windows machine, so I can't confirm unfortunately :sweat: 

I googled for the message, ie "Microsoft.Cpp.Default.props was not found", which lead me to http://stackoverflow.com/questions/21069699/node-packages-not-building-on-windows-8-1-missing-microsoft-cpp-default-props via https://github.com/apiaryio/protagonist/issues/33

**Comment by ccoenen** [comment]
Trying this out on windows 10, I can confirm that the regular way works as intended. I did get similar error messages from one adapter (hubot-irc in my case), so I would guess that generator-hubot is not at fault, here.
