### ISSUE TITLE
Dependency on download package is missing

### ISSUE THREAD

**Issue by cyberwolf** [hubotio/generator-hubot#60]
When trying to run yo hubot I got this error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'download'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/generator-hubot/node_modules/yeoman-generator/lib/actions/fetch.js:3:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

It appears like the dependency on the _download_ package is missing.

If I first install the download package, you hubot starts working correctly.

```
npm install -g download
```

**Comment by technicalpickles** [comment]
I haven't seen this one. I think it's a probably a problem with `yo`. Can you try `npm install -g yo` again and see if it helps?

**Comment by cyberwolf** [comment]
Haven't looked at this in a while so probably it's not a problem (any longer), so closing.
